name = "ficsitprints"
main = "worker.js"
compatibility_date = "2026-07-04"

[assets]
directory = "public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "ficsitprints"
database_id = "1a507b03-94e2-4fdb-938d-b23b3af3df2c"
